/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as RegisterVendorRouteImport } from './routes/register.vendor'
import { Route as StudentOrdersRouteImport } from './routes/student.orders'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVendorRoute = RegisterVendorRouteImport.update({
  id: '/register/vendor',
  path: '/register/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOrdersRoute = StudentOrdersRouteImport.update({
  id: '/student/orders',
  path: '/student/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/item/$id': typeof ItemIdRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/vendor': typeof RegisterVendorRoute
  '/student/orders': typeof StudentOrdersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/item/$id': typeof ItemIdRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/vendor': typeof RegisterVendorRoute
  '/student/orders': typeof StudentOrdersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/item/$id': typeof ItemIdRoute
  '/register/student': typeof RegisterStudentRoute
  '/register/vendor': typeof RegisterVendorRoute
  '/student/orders': typeof StudentOrdersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/checkout/$id'
    | '/item/$id'
    | '/register/student'
    | '/register/vendor'
    | '/student/orders'
    | '/vendor/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/checkout/$id'
    | '/item/$id'
    | '/register/student'
    | '/register/vendor'
    | '/student/orders'
    | '/vendor/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/checkout/$id'
    | '/item/$id'
    | '/register/student'
    | '/register/vendor'
    | '/student/orders'
    | '/vendor/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ItemIdRoute: typeof ItemIdRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  RegisterVendorRoute: typeof RegisterVendorRoute
  StudentOrdersRoute: typeof StudentOrdersRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/vendor': {
      id: '/register/vendor'
      path: '/register/vendor'
      fullPath: '/register/vendor'
      preLoaderRoute: typeof RegisterVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/orders': {
      id: '/student/orders'
      path: '/student/orders'
      fullPath: '/student/orders'
      preLoaderRoute: typeof StudentOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ItemIdRoute: ItemIdRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  RegisterVendorRoute: RegisterVendorRoute,
  StudentOrdersRoute: StudentOrdersRoute,
  VendorDashboardRoute: VendorDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
